# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'  

variables:
  SONARQUBE_HOST_URL: $(SONARQUBE_HOST_URL)
  SONARQUBE_TOKEN: $(SONARQUBE_TOKEN)

steps:

# Instalar Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Instalar Node.js'

# Instalar dependencias
- script: |
    npm ci
  displayName: 'Instalar dependencias'

#Run SonarQ
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'svc-son'
    scannerMode: 'cli'
    cliScannerVersion: '7.1.0.488'
    configMode: 'manual'
    cliProjectKey: 'react-nginx-app'
    cliProjectName: 'React NGINX App'
    cliSources: 'src'
    extraProperties: 
     sonar.exclusions=node_modules/**,build/**,dist/**
     sonar.javascript.lcov.reportPaths=coverage/lcov.info
- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'
# Compilar la app de React
- script: |
    npm run build
  displayName: 'Compilar app React'
